config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :users, :only => [:index] do
    resources :posts
  end

  resources :users, :only => [:show] do
    resources :tags
  end

  resources :posts do

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :asset, styles: { medium: "300x300>", small: "140x140>", thumb: "64x64!" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :asset, content_type: /\Aimage\/.*\z/

  has_many :tags
  has_many :users, through: :tags

  validates :owner_id, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tags
  has_many :posts, through: :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
    @posts = Post.where(owner_id: current_user.id)
    @post = Post.new
    @user = current_user.id
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(asset: post_params[:asset], name: post_params[:name], content: post_params[:content], owner_id: current_user.id)
    if @post.save
      redirect_to "/"
      flash[:notice] = "Post successful!"
    else
      redirect_to new_user_post_path(current_user)
      flash[:alert] = "Upload failed"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(asset: post_params[:asset], name: post_params[:name], content: post_params[:content], owner_id: current_user.id)
      flash[:notice] = "Changes saved"
      redirect_to "/"
    else
      flash[:alert] = "Changes were not saved"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to "/"
  end

private
  def post_params
    params.require(:post).permit(:asset, :name, :content)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Discover</h1>

<% if @posts.any? %>
  <% @posts.each do |post| %>
    <%= link_to image_tag(post.asset.url(:small)), user_post_path(post.owner_id, post) %>
  <% end %>
<% else %>
  <p>There are no posts yet!</p>
<% end %>
<%= link_to "New Post", new_user_post_path(current_user) %>
<%= link_to "My Posts", user_posts_path(current_user, @posts) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnFlicked</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
       <a href="/" class="brand-logo">UnFlicked</a>
       <ul id="nav-mobile" class="right hide-on-med-and-down">
         <% if user_signed_in? %>
           Hi <%= current_user.email %>!
           <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
           <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
         <% else %>
           <li><%= link_to "Sign-up", new_user_registration_path %></li>
           <li><%= link_to "Login", new_user_session_path %></li>
         <% end %>
       </ul>
     </div>
    </nav>
    <div class="container">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.file_field :asset %><br>

  <%= f.submit "Save", class: "btn" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "layouts/errors", :object => @post %>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Post Index</h1>

<% if @posts.any? %>
  <% @posts.each do |post| %>
    <%= link_to image_tag(post.asset.url(:small)), user_post_path(post.owner_id, post) %>
  <% end %>
<% else %>
  <p>There are no posts yet!</p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "layouts/errors", :object => @post %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.file_field :asset %><br>

  <%= f.submit "Save", class: "btn" %>
<% end %>

app/views/posts/show.html.erb
<h1>Post</h1>

<%= image_tag @post.asset.url(:medium) %><br>
<h4><%= @post.name %></h4>
<p><%= @post.content %></p>

<% if user_signed_in? %>
  <% if current_user.id == @post.owner_id %>
    <p><%= link_to "Edit", edit_user_post_path(current_user.id, @post) %></p>
    <p><%= link_to "Delete", user_post_path(current_user.id, @post),
                             :data => {:confirm => "Really?",
                                       :method => "delete"} %></p>
   <% end %>
 <% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>